- hosts: localhost
  tasks:
   - name: 1.1.18 - Ensure sticky bit is set on all world-writable directories - changed_when false
     shell: echo "hello"
     register: hello

   - debug: 
       var: "hello.stdout_lines"
     changed_when: False
